### ISSUE TITLE
Running any NuScene Model throws AssertionError

### ISSUE THREAD

**Issue by fjahncke** [Kin-Zhang/OpenPCDet_ros#1]
First off all thanks for this amazing repo. It was super easy to install and integrate in my perception pipeline. For cone detection I would like to run models like PointPillars trained on the NuScenes datasets. All models I try from KITTI work fine, but all from NuScenes throw this error:
`[ERROR] [1676287436.802183]: bad callback: <function rslidar_callback at 0x7f953e265dc0>
Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/felix/workspace/OpenPCDet_ws/src/OpenPCDet_ros/src/inference.py", line 178, in rslidar_callback
    scores, dt_box_lidar, types, pred_dict = proc_1.run(np_p, calib, frame)
  File "/home/felix/workspace/OpenPCDet_ws/src/OpenPCDet_ros/src/inference.py", line 297, in run
    data_dict = self.demo_dataset.prepare_data(data_dict=input_dict)
  File "/home/felix/OpenPCDet/pcdet/datasets/dataset.py", line 180, in prepare_data
    data_dict = self.point_feature_encoder.forward(data_dict)
  File "/home/felix/OpenPCDet/pcdet/datasets/processor/point_feature_encoder.py", line 29, in forward
    data_dict['points'], use_lead_xyz = getattr(self, self.point_encoding_config.encoding_type)(
  File "/home/felix/OpenPCDet/pcdet/datasets/processor/point_feature_encoder.py", line 48, in absolute_coordinates_encoding
    assert points.shape[-1] == len(self.src_feature_list)
AssertionError
`

Is this a problem in the driver or OpenPCDet?
Im running it online on a Velodyne M1600 and Ouster OS1 with a laptop and NVIDIA RTX 3070. I changed the file paths accordingly for both NuScenes and KITTI

**Comment by Kin-Zhang** [comment]
Oh, I think I didn't try Nuscenes, either. Maybe there are config file need change, could you please send a teaser bag file for me try?

**Comment by fjahncke** [comment]
Great I just send you an email

**Comment by Kin-Zhang** [comment]
Ok I think the problem is you need change the config file, no timestamp in your bag pcd file so we can modify 
dataset.yaml here:
```yaml
POINT_FEATURE_ENCODING: {
    encoding_type: absolute_coordinates_encoding,
    used_feature_list: ['x', 'y', 'z', 'intensity'],
    src_feature_list: ['x', 'y', 'z', 'intensity'],
}
```

And I run success in your data, but the probability is really low so that's also why no rivz show:

![image](https://user-images.githubusercontent.com/35365764/219666074-fdd7149d-38de-4f34-9010-945673a0f642.png)

But the kitti dataset and model probability is like this one, almost of them are higher than 0.8 which 80%
![image](https://user-images.githubusercontent.com/35365764/219666527-6a8fde6e-0f89-4ba3-9d74-dcbfbc3772bc.png)

**Comment by fjahncke** [comment]
Thanks for the quick response and fix. The probability is so low that and the algorithm doesnt detect any cones that I used the custom dataset format from OpenPCDet, labeled my pointclouds and trained some models on my rosbag which works fantastic with your ROS implementation.
