### ISSUE TITLE
Error running program

### ISSUE THREAD

**Issue by Parkeunseok** [Kin-Zhang/OpenPCDet_ros#11]
Hello, the following error occurs when I download and execute your project. Below is my computer specification.

CPU : intel i7-12700K

GPU : NVIDIA RTX 3080 

How do I solve this??

![error](https://github.com/Kin-Zhang/OpenPCDet_ros/assets/87689132/32dfc38d-4300-4f9e-9481-29029415f00a)

**Comment by Kin-Zhang** [comment]
Looks like it’s out of memory which means at least 12G GPU memory to run….
