### ISSUE TITLE
How to choose move_lidar_center param in config.yaml

### ISSUE THREAD

**Issue by josyulavt** [Kin-Zhang/OpenPCDet_ros#13]
As the title says, I'm unsure how to choose this parameter, currently I'm relying on guess work or leaving the default to 20. what is the right way to choose this number?

**Comment by Kin-Zhang** [comment]
Hi I don't think `move_lidar_center` matter, as I noted down in the README I also confused about this when I refactor others' code. After I took a quick look, I found out it's only used in `self.points[:,0] += move_lidar_center` which only move x-axis?

So I think you can try comment it out to see if it's ok? I will also try it and back the result recently.

**Comment by josyulavt** [comment]
Thank you for the response, if I give `move_lidar_center=0` the detection bounding boxes are output in wrong location, I am having to set to 20 to get the right locations therefore commenting out doesn't help.

**Comment by Kin-Zhang** [comment]
It's because draw 3d box -move_lidar_center...

![image](https://github.com/user-attachments/assets/3c880ee8-92c1-4bbe-92df-125a330c1cd5)


I think you can set 0 in the config file?

**Comment by Kin-Zhang** [comment]
I already pushed two commits and update the code, remove all shift param and tested in my local that results are correct in kitti with default weight and model.

While rviz visualization may delay bbx vis, I stop at bag sometimes and checked bbx vis in the frame is correct. For example:

![image](https://github.com/user-attachments/assets/e592be93-b1db-471f-92c5-692144b3d985)

**Comment by josyulavt** [comment]
thank you very much, I'm using a custom dataset, I'll have to request for a machine to test this. I'll confirm when I get to test.

**Comment by Kin-Zhang** [comment]
No worries, let me know if you have any problems afterward.
