### ISSUE TITLE
No detection result show in rviz when using custom dataset.

### ISSUE THREAD

**Issue by Jane-QinJ** [Kin-Zhang/OpenPCDet_ros#15]
Dear author,

Thank you for your great work!

I want to use openpcdet custom dataset to train my own model. It works well and I get the result and the demo.py shows it is correctly detected.
![Screenshot from 2024-07-22 20-36-47](https://github.com/user-attachments/assets/9c7fe443-cfd8-44d5-a1f2-107241047461)

But when I load the model and run it on ros topic, it can't detect any target.

The possible reason maybe cause by the data transferring. In order to using[ custom dataset form](https://github.com/open-mmlab/OpenPCDet/blob/master/docs/CUSTOM_DATASET_TUTORIAL.md) I transfer the point cloud from pcd to bin and then finally transfer it into npy. 

And the label format is: 
5.54 0.57 0.41 1.08 0.74 1.95 1.57 Pedestrian.

Here is my bag info:

path:        od_1.bag
version:     2.0
duration:    2:56s (176s)
start:       May 10 2024 06:10:04.21 (1715321404.21)
end:         May 10 2024 06:13:00.89 (1715321580.89)
size:        7.0 GB
messages:    8454
compression: none [1766/1766 chunks]
types:       bond/Status                           [eacc84bf5d65b6777d4c50f463dfb9c8]
             diagnostic_msgs/DiagnosticArray       [60810da900de1dd6ddd437c3503511da]
             dynamic_reconfigure/Config            [958f16a05573709014982821e6822580]
             dynamic_reconfigure/ConfigDescription [757ce9d44ba8ddd801bb30bc456f946f]
             rosgraph_msgs/Log                     [acffd30cd6b6de30f120938c17c593fb]
             sensor_msgs/LaserScan                 [90c7ef2dc6895d81024acba2ac42f369]
             sensor_msgs/PointCloud2               [1158d486dd51d683ce2f1be655c3c181]
             tf2_msgs/TFMessage                    [94810edda583a504dfda3829e70d7eec]
             velodyne_msgs/VelodyneScan            [50804fc9533a0e579e6322c04ae70566]
topics:      /diagnostics                                                  350 msgs    : diagnostic_msgs/DiagnosticArray      
             /hesai/pandar                                                1765 msgs    : sensor_msgs/PointCloud2              
             /rosout                                                        23 msgs    : rosgraph_msgs/Log                     (2 connections)
             /rosout_agg                                                     5 msgs    : rosgraph_msgs/Log                    
             /scan                                                        1741 msgs    : sensor_msgs/LaserScan                
             /tf_static                                                      1 msg     : tf2_msgs/TFMessage                   
             /velodyne_nodelet_manager/bond                               1062 msgs    : bond/Status                           (4 connections)
             /velodyne_nodelet_manager_driver/parameter_descriptions         1 msg     : dynamic_reconfigure/ConfigDescription
             /velodyne_nodelet_manager_driver/parameter_updates              1 msg     : dynamic_reconfigure/Config           
             /velodyne_nodelet_manager_laserscan/parameter_descriptions      1 msg     : dynamic_reconfigure/ConfigDescription
             /velodyne_nodelet_manager_laserscan/parameter_updates           1 msg     : dynamic_reconfigure/Config           
             /velodyne_nodelet_manager_transform/parameter_descriptions      1 msg     : dynamic_reconfigure/ConfigDescription
             /velodyne_nodelet_manager_transform/parameter_updates           1 msg     : dynamic_reconfigure/Config           
             /velodyne_packets                                            1751 msgs    : velodyne_msgs/VelodyneScan           
             /velodyne_points                                             1750 msgs    : sensor_msgs/PointCloud2
.
Is there any influence to detection result? Since in the rosbag, the point cloud message is always sensor_msgs/PointCloud2.

I'm very confused and hope you can help me figure out.

Looking forward to your reply.

A lot of thanks!

**Comment by Kin-Zhang** [comment]
Hi Jane,

Could you print out few points data in demo.py and also in inference.py where ROS callback to check if the point data is correct? and I pushed two commits for removing shift, could you please try again `git pull` and run the checking step?

**Comment by Jane-QinJ** [comment]
> Hi Jane,
> 
> Could you print out few points data in demo.py and also in inference.py where ROS callback to check if the point data is correct? and I pushed two commits for removing shift, could you please try again `git pull` and run the checking step?

Thank you for your kind respond :heart: 

I try to print the point data in demo.py, and I found something strange. First, the .bin and .npy of the same point cloud frame is not consist.  Second, the detection result is also strange, it can detect human in the bin format but not in the npy format. But I train the model in the npy format. Here's the result: 

**for bin:**
Points data for sample 0:
[[-1.16609605e-02  5.06064236e-01  6.21533729e-02  6.20000000e+01]
 [ 9.00401175e-02  9.41995263e-01  1.83939874e-01  5.00000000e+00]
 [ 9.37152505e-02  9.45582509e-01  1.84703112e-01  5.00000000e+00]
 ...
 [-9.41023064e+00 -7.63658619e+00 -1.48802483e+00  2.00000000e+00]
 [-9.32731438e+00 -7.51813745e+00 -1.47096312e+00  2.00000000e+00]
 [-9.32560444e+00 -7.46320438e+00 -1.46657574e+00  2.00000000e+00]]

Detection r
![Screenshot from 2024-07-23 18-36-12](https://github.com/user-attachments/assets/50b6a0f6-a329-4bbd-b63a-4db0bba8b6dc)
esult:

**for npy:**
cd tools && python3 demo.py --cfg_file cfgs/custom_models/pointpillar.yaml --ckpt ../output/custom_models/pointpillar/kizu_detection80e/ckpt/checkpoint_epoch_80.pth --data_path ../data/custon/points/000379.npy

Points data for sample 0:
[[ 2.2366853e+08  1.2387478e-40  3.4833497e-15  4.4898648e+21]
 [ 1.5767864e-19  2.1442303e-07  2.2228396e-15  7.6830766e+31]
 [ 1.7177136e+19  6.7425655e+22  1.5767864e-19  1.8727951e+31]
 ...
 [-9.4102306e+00 -7.6365862e+00 -1.4880248e+00  2.0000000e+00]
 [-9.3273144e+00 -7.5181375e+00 -1.4709631e+00  2.0000000e+00]
 [-9.3256044e+00 -7.4632044e+00 -1.4665757e+00  2.0000000e+00]]

Detection result:
![Screenshot from 2024-07-23 18-38-57](https://github.com/user-attachments/assets/8026ba2c-c276-440a-b09d-63138ce4b49e)

I also print the points in inference.py where ROS callback. But since the bag playing confusing me about the timestamp, I can't make sure it is the same sample with the demo one. So I just pick one randomly. Here's the result:

Points data received for frame 533:
[[ 3.88242388 -2.26234698 -1.20402634  0.        ]
 [ 3.89224625 -2.2689805   0.07864054  0.        ]
 [ 3.4156003  -1.99191928 -0.91285139  0.        ]
 ...
 [ 3.88388133 -2.54929256  1.07256663  0.        ]
 [ 3.89805841 -2.55957222 -0.08139802  0.        ]
 [ 3.88486195 -2.55187726  1.24543726  0.        ]]

Although it is not the same frame with the bin and npy, there is difference. It is different from either bin or npy since there is no intensity value. Maybe this is why the model perform not well in ros?

Also I'm more confused about the different type of point cloud representations. I use opensource tool to extract pcd from bag, and then do the following transfering: pcd->bin->npy. But I don't understand why the bin and npy result isn't the same. Is there something wrong with my processing?

Here's the pcd to bin code:
```
import os
import numpy as np
from pypcd import pypcd

# Define the input directory containing the .pcd files
input_directory = '/home/firo/Downloads/label_tranfer/lidar/own_data/sorted_lidar'
# Define the output directory where the .bin files will be saved
output_directory = '/home/firo/Downloads/label_tranfer/lidar/own_data/bin'

# Ensure the output directory exists
os.makedirs(output_directory, exist_ok=True)

# Function to process a single .pcd file and save it as a .bin file
def process_pcd_file(input_file_path, output_file_path):
    # Read point cloud data from the .pcd file
    pcd_data = pypcd.PointCloud.from_path(input_file_path)

    # Initialize a numpy array to store the points (x, y, z, intensity)
    points = np.zeros([pcd_data.width, 4], dtype=np.float32)

    # Copy the x, y, z coordinates and intensity values into the numpy array
    points[:, 0] = pcd_data.pc_data['x'].copy()
    points[:, 1] = pcd_data.pc_data['y'].copy()
    points[:, 2] = pcd_data.pc_data['z'].copy()
    points[:, 3] = pcd_data.pc_data['intensity'].copy().astype(np.float32)

    # Write the numpy array to the binary file
    with open(output_file_path, 'wb') as f:
        f.write(points.tobytes())

# Loop through all files in the input directory
for filename in os.listdir(input_directory):
    if filename.endswith('.pcd'):
        # Construct the full input and output file paths
        input_file_path = os.path.join(input_directory, filename)
        output_file_path = os.path.join(output_directory, f"{os.path.splitext(filename)[0]}.bin")

        # Process the .pcd file and save it as a .bin file
        process_pcd_file(input_file_path, output_file_path)

print("Batch processing of .pcd files is complete.")
```

Here's the bin to npy code:

```
import numpy as np
import os

def bin_to_npy(bin_file_path, npy_file_path, dtype, shape):
    try:
        # Read the binary file
        with open(bin_file_path, 'rb') as bin_file:
            bin_data = bin_file.read()

        # Convert binary data to a NumPy array
        data_array = np.frombuffer(bin_data, dtype=dtype)

        # Reshape the array to the desired shape (if provided)
        if shape:
            data_array = data_array.reshape(shape)

        # Save the array to a .npy file
        np.save(npy_file_path, data_array)

        print(f"Successfully converted {bin_file_path} to {npy_file_path}")
    except FileNotFoundError:
        print(f"Error: The file {bin_file_path} was not found.")
    except Exception as e:
        print(f"An error occurred: {e}")

def batch_process_bin_to_npy(input_folder, output_folder, dtype, shape):
    # Create the output folder if it does not exist
    if not os.path.exists(output_folder):
        os.makedirs(output_folder)

    # Process each binary file in the input folder
    for file_name in os.listdir(input_folder):
        if file_name.endswith(".bin"):
            bin_file_path = os.path.join(input_folder, file_name)
            npy_file_name = os.path.splitext(file_name)[0] + ".npy"
            npy_file_path = os.path.join(output_folder, npy_file_name)
            bin_to_npy(bin_file_path, npy_file_path, dtype, shape)

# Example usage
input_folder = '/home/firo/Downloads/label_tranfer/lidar/own_data/bin'  # Replace with your input folder path
output_folder = '/home/firo/Downloads/label_tranfer/lidar/own_data/npy'  # Replace with your output folder path
dtype = np.float32  # Replace with the correct data type
shape = (-1, 4)  # Replace with the correct shape, or set to None if not reshaping

batch_process_bin_to_npy(input_folder, output_folder, dtype, shape)
```

**Comment by Kin-Zhang** [comment]
Based on the pull request, I think maybe solved. should we close it? @Jane-QinJ

**Comment by Jane-QinJ** [comment]
Yes, we can close it, thank you for your help again!

获取 Outlook for iOS<https://aka.ms/o0ukef>

________________________________
发件人: ***@***.*** ***@***.***> 代表 Qingwen Zhang ***@***.***>
发送时间: 星期三, 八月 14, 2024 1:24 上午
收件人: OpenPCDet_ros ***@***.***>
抄送: 1139804380 ***@***.***>; mention ***@***.***>
主题: Re: [Kin-Zhang/OpenPCDet_ros] No detection result show in rviz whenusing custom dataset. (Issue #15)


Based on the pull request, I think maybe solved. should we close it? @Jane-QinJ<https://github.com/Jane-QinJ>

―
