### ISSUE TITLE
erro: scores, dt_box_lidar, types, pred_dict = proc_1.run(np_p, frame)

### ISSUE THREAD

**Issue by mendoza-G** [Kin-Zhang/OpenPCDet_ros#2]
length of proc_1.run(np_p, frame) is 10 :
![image](https://user-images.githubusercontent.com/81526517/219925949-01f493bc-503c-4109-a41e-110a095c4d3c.png)
![image](https://user-images.githubusercontent.com/81526517/219925981-d3f4b98f-e955-448d-89d5-e322a6b5c205.png)
how should I modify, thanks~

**Comment by mendoza-G** [comment]
https://github.com/Kin-Zhang/OpenPCDet_ros/blob/8343c1d70287fd5cb15b62ce34894d3bddb89aad/src/inference.py#L233
I 've found where the issue come:
 if scores.shape[0] == 0:
            return pred_dict
so I get the full  pred_dict.

**Comment by Kin-Zhang** [comment]
Thanks for pointing that out. fix in 110b6d24975420d8de4b460830bfc7ead8636d50

**Comment by yang-jiaye** [comment]
> https://github.com/Kin-Zhang/OpenPCDet_ros/blob/8343c1d70287fd5cb15b62ce34894d3bddb89aad/src/inference.py#L233
> 
> I 've found where the issue come:
> if scores.shape[0] == 0:
> return pred_dict
> so I get the full pred_dict.

same problem，thank you for your work
