### ISSUE TITLE
PV-RCNN

### ISSUE THREAD

**Issue by graiola** [Kin-Zhang/OpenPCDet_ros#4]
Hi, maybe it is a stupid question but where can I find `pv_rcnn_8369.pth`? Thank you!

**Comment by graiola** [comment]
found it at https://drive.google.com/file/d/1lIOq4Hxr0W3qsX83ilQv0nk1Cls6KAr-/view?usp=sharing

**Comment by Kin-Zhang** [comment]
https://github.com/open-mmlab/OpenPCDet#model-zoo

![image](https://user-images.githubusercontent.com/35365764/231377848-fccc0b1d-836e-4999-993d-8769a2c14d04.png)
