### ISSUE TITLE
预测标签可视化

### ISSUE THREAD

**Issue by LinTengX** [Kin-Zhang/OpenPCDet_ros#6]
博主您好，我想要将预测框的类别也在场景中可视化出来，我应该怎么做

**Comment by Kin-Zhang** [comment]
本来应该一口气做完的 我reference的AI葵里的video有讲怎么做 感兴趣的话 可以做完pull request过来  😊

**Comment by Kin-Zhang** [comment]
已完成，查看最新commit可获取 （git pull）

https://github.com/Kin-Zhang/OpenPCDet_ros/commit/b455aafd423aebdf2e915cab8740fe1654e3b7c6

![example](https://github.com/Kin-Zhang/OpenPCDet_ros/assets/35365764/33710fb7-a715-4daf-bbb4-b0238452cfaf)
