### ISSUE TITLE
Missing version.py in pcdet directory

### ISSUE THREAD

**Issue by SharimieAdam** [Kin-Zhang/OpenPCDet_ros#8]
Issue Description:
While trying to run the demo.py script, I encountered an error that states a module named pcdet could not be found. Upon investigating, I noticed that the version.py file is missing in the pcdet directory of my cloned repository.

Steps to Reproduce:

Clone the OpenPCDet repository.
Navigate to the tools directory.
Run the demo.py script.
The error message appears indicating a missing version.py.
Expected Behavior:
The demo.py script should run without errors related to missing modules or files.

Actual Behavior:
Received an error indicating that version.py is missing from the pcdet directory.

Environment:

Docker image: zhangkin/openpcdet:ros
OS: Ubuntu 20.04 (Running on WSL2)
GPU: RTX4090

Attachments:
![Screenshot 2023-09-15 102017](https://github.com/Kin-Zhang/OpenPCDet_ros/assets/117331471/27d0e77e-a99b-4fb1-b31f-37626beeb2fb)

Additional Notes:
I tried a workaround by replacing references to version.py in demo.py, but the issue persisted.

please help me

**Comment by Kin-Zhang** [comment]
Maybe you can try to git clone the commit I fork: 
> OpenPCDet Version: [fork in Kin-Zhang/OpenPCDet](https://github.com/Kin-Zhang/OpenPCDet), commit: [977cd1c](https://github.com/Kin-Zhang/OpenPCDet/commit/977cd1c19df2a357765f9f013b9c9fd46d907f88)

Then you need run! install OpenPCDet to your python first
```
cd OpenPCDet && python3 setup.py develop
```
